"use client"

import type React from "react"
import { useState, useRef, useEffect } from "react"
import { Sparkles, User, Send, TestTube, Zap, ArrowDown } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { ArtifactCard } from "@/components/artifact-card"
import { ArtifactViewer } from "@/components/artifact-viewer"
import type { ChatMessageWithArtifacts, Artifact } from "@/lib/types"
import { sampleMessages } from "@/lib/test-data"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"

export default function ChatPage() {
  const [isTestMode, setIsTestMode] = useState(true)
  const [messages, setMessages] = useState<ChatMessageWithArtifacts[]>(isTestMode ? sampleMessages : [])
  const [input, setInput] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const [selectedArtifact, setSelectedArtifact] = useState<Artifact | null>(null)
  const [showScrollButton, setShowScrollButton] = useState(false)

  const scrollContainerRef = useRef<HTMLDivElement>(null)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const isUserScrollingRef = useRef(false)

  const scrollToBottom = (behavior: ScrollBehavior = "smooth") => {
    messagesEndRef.current?.scrollIntoView({ behavior, block: "end" })
  }

  useEffect(() => {
    // Only auto-scroll if user hasn't manually scrolled up
    if (!isUserScrollingRef.current) {
      scrollToBottom("smooth")
    }
  }, [messages, isLoading])

  const handleScroll = () => {
    if (!scrollContainerRef.current) return

    const { scrollTop, scrollHeight, clientHeight } = scrollContainerRef.current

    // Check if user is near bottom (within 100px)
    const isNearBottom = scrollHeight - scrollTop - clientHeight < 100

    setShowScrollButton(!isNearBottom)
    isUserScrollingRef.current = !isNearBottom
  }

  useEffect(() => {
    const scrollContainer = scrollContainerRef.current
    if (scrollContainer) {
      scrollContainer.addEventListener("scroll", handleScroll)
      return () => scrollContainer.removeEventListener("scroll", handleScroll)
    }
  }, [])

  const toggleTestMode = () => {
    const newTestMode = !isTestMode
    setIsTestMode(newTestMode)
    setMessages(newTestMode ? sampleMessages : [])
    setSelectedArtifact(null)
    isUserScrollingRef.current = false
    setTimeout(() => scrollToBottom("auto"), 100)
  }

  const handleSendMessage = async () => {
    if (!input.trim() || isLoading) return

    const userMessage: ChatMessageWithArtifacts = {
      id: Date.now().toString(),
      role: "user",
      content: input,
      timestamp: new Date(),
    }

    setMessages((prev) => [...prev, userMessage])
    setInput("")
    setIsLoading(true)
    isUserScrollingRef.current = false

    if (isTestMode) {
      setTimeout(() => {
        const assistantMessage: ChatMessageWithArtifacts = {
          id: (Date.now() + 1).toString(),
          role: "assistant",
          content:
            "This is a test response. In production, this would be generated by the AI. Toggle test mode off to use real AI responses.",
          timestamp: new Date(),
        }
        setMessages((prev) => [...prev, assistantMessage])
        setIsLoading(false)
      }, 1000)
      return
    }

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: input, mode: "chat" }),
      })

      const data = await response.json()

      const artifacts: Artifact[] = []
      const content = data.response

      // Simple artifact detection (in real implementation, this would be more sophisticated)
      const codeBlockRegex = /```(\w+)\n([\s\S]*?)```/g
      let match
      let artifactIndex = 0

      while ((match = codeBlockRegex.exec(data.response)) !== null) {
        const [fullMatch, language, code] = match
        const artifact: Artifact = {
          id: `artifact-${Date.now()}-${artifactIndex++}`,
          type: language as Artifact["type"],
          title: `${language.toUpperCase()} Code`,
          content: code.trim(),
          language,
        }
        artifacts.push(artifact)
      }

      const assistantMessage: ChatMessageWithArtifacts = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content,
        timestamp: new Date(),
        artifacts: artifacts.length > 0 ? artifacts : undefined,
      }

      setMessages((prev) => [...prev, assistantMessage])
    } catch (error) {
      console.error("Failed to send message:", error)
    } finally {
      setIsLoading(false)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault()
      handleSendMessage()
    }
  }

  return (
    <div className="flex h-full flex-col">
      <div className="flex items-center justify-between border-b border-border bg-muted/30 px-4 py-2">
        <div className="flex items-center gap-2">
          <div
            className={`flex items-center gap-2 rounded-md px-3 py-1.5 text-sm ${isTestMode ? "bg-amber-500/10 text-amber-600 dark:text-amber-400" : "bg-green-500/10 text-green-600 dark:text-green-400"}`}
          >
            {isTestMode ? (
              <>
                <TestTube className="h-4 w-4" />
                <span className="font-medium">Test Mode</span>
              </>
            ) : (
              <>
                <Zap className="h-4 w-4" />
                <span className="font-medium">Live Mode</span>
              </>
            )}
          </div>
          <span className="hidden text-xs text-muted-foreground md:inline">
            {isTestMode
              ? "Using sample data for testing layout and interactions"
              : "Connected to AI service for real responses"}
          </span>
        </div>
        <Button variant="outline" size="sm" onClick={toggleTestMode}>
          Switch to {isTestMode ? "Live" : "Test"} Mode
        </Button>
      </div>

      <div className="flex flex-1 overflow-hidden">
        <div
          className={`flex flex-col transition-all duration-300 ease-in-out min-w-0 ${
            selectedArtifact
              ? "w-full lg:w-[45%]" // On desktop, take 45% when artifact is open
              : "w-full" // Take full width when artifact is closed
          }`}
        >
          <div ref={scrollContainerRef} className="flex-1 overflow-y-auto overflow-x-hidden">
            <div
              className={`mx-auto space-y-6 p-6 break-words min-w-0 overflow-hidden ${
                selectedArtifact ? "max-w-full px-3 sm:px-4 md:px-6" : "max-w-3xl"
              }`}
            >
              {messages.length === 0 && (
                <div className="flex flex-col items-center justify-center py-12 text-center">
                  <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary/10">
                    <Sparkles className="h-8 w-8 text-primary" />
                  </div>
                  <h2 className="mb-2 text-2xl font-semibold">AI Chat</h2>
                  <p className="text-muted-foreground">
                    Start a conversation with AI. Create documents, write code, and get instant help.
                  </p>
                  <p className="mt-4 text-sm text-muted-foreground">
                    Currently in <span className="font-medium">{isTestMode ? "Test" : "Live"}</span> mode.{" "}
                    {isTestMode && "Sample messages will appear when you toggle test mode."}
                  </p>
                </div>
              )}

              {messages.map((message) => (
                <div key={message.id} className="flex gap-4 min-w-0 overflow-hidden">
                  <div className="flex-shrink-0">
                    <div
                      className={`flex h-8 w-8 items-center justify-center rounded-full ${
                        message.role === "user" ? "bg-primary" : "bg-primary/10"
                      }`}
                    >
                      {message.role === "user" ? (
                        <User className="h-4 w-4 text-primary-foreground" />
                      ) : (
                        <Sparkles className="h-4 w-4 text-primary" />
                      )}
                    </div>
                  </div>

                  <div className="flex-1 space-y-3 min-w-0 overflow-hidden">
                    <div className="text-sm font-medium">{message.role === "user" ? "You" : "AI Assistant"}</div>

                    <div className="prose prose-sm max-w-none break-words [overflow-wrap:anywhere] dark:prose-invert">
                      <ReactMarkdown
                        remarkPlugins={[remarkGfm]}
                        components={{
                          code: ({ node, inline, className, children, ...props }) => {
                            return inline ? (
                              <code className="rounded bg-muted px-1.5 py-0.5 text-sm break-all" {...props}>
                                {children}
                              </code>
                            ) : null
                          },
                        }}
                      >
                        {message.content}
                      </ReactMarkdown>
                    </div>

                    {message.artifacts && message.artifacts.length > 0 && (
                      <div className="space-y-2 min-w-0 overflow-hidden w-full max-w-full">
                        {message.artifacts.map((artifact) => (
                          <ArtifactCard
                            key={artifact.id}
                            artifact={artifact}
                            onSelect={() => setSelectedArtifact(artifact)}
                          />
                        ))}
                      </div>
                    )}

                    <div className="text-xs text-muted-foreground">
                      {message.timestamp.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                    </div>
                  </div>
                </div>
              ))}

              {isLoading && (
                <div className="flex gap-4">
                  <div className="flex-shrink-0">
                    <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10">
                      <Sparkles className="h-4 w-4 animate-pulse text-primary" />
                    </div>
                  </div>
                  <div className="flex-1 space-y-3">
                    <div className="text-sm font-medium">AI Assistant</div>
                    <div className="flex items-center gap-2">
                      <div className="h-2 w-2 animate-bounce rounded-full bg-primary/60 [animation-delay:-0.3s]" />
                      <div className="h-2 w-2 animate-bounce rounded-full bg-primary/60 [animation-delay:-0.15s]" />
                      <div className="h-2 w-2 animate-bounce rounded-full bg-primary/60" />
                    </div>
                  </div>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>
          </div>

          {showScrollButton && (
            <div className="absolute bottom-24 right-4 z-10 lg:right-8">
              <Button
                onClick={() => {
                  isUserScrollingRef.current = false
                  scrollToBottom("smooth")
                }}
                size="icon"
                className="h-10 w-10 rounded-full shadow-lg"
                variant="secondary"
              >
                <ArrowDown className="h-4 w-4" />
              </Button>
            </div>
          )}

          <div className="border-t border-border bg-background p-4">
            <div className={`mx-auto min-w-0 ${selectedArtifact ? "max-w-full px-0 sm:px-2" : "max-w-3xl"}`}>
              <div className="flex gap-2">
                <Textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Message AI..."
                  className="min-h-[60px] resize-none"
                  disabled={isLoading}
                />
                <Button
                  onClick={handleSendMessage}
                  disabled={isLoading || !input.trim()}
                  size="icon"
                  className="h-[60px] flex-shrink-0"
                >
                  <Send className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        </div>

        {selectedArtifact && (
          <div
            className={`
              hidden lg:flex lg:w-[55%]
              border-l border-border
              transition-all duration-300 ease-in-out
            `}
          >
            <ArtifactViewer artifact={selectedArtifact} onClose={() => setSelectedArtifact(null)} />
          </div>
        )}

        {selectedArtifact && (
          <div className="fixed inset-0 z-50 bg-background lg:hidden">
            <ArtifactViewer artifact={selectedArtifact} onClose={() => setSelectedArtifact(null)} />
          </div>
        )}
      </div>
    </div>
  )
}
